title: Temporal Sciences Wiki
description: The Temporal Sciences canon remains open, evolving, and subject to continuous refinement.
theme: minima
markdown: kramdown
url: "https://www.temporalsciences.wiki"
baseurl: ""   # leave empty if using a custom domain or user site

header_pages:
  - index.md
  - documents.md
  - links.md
